chats/urls.py
from django.urls import path
from chats import views
from chats.views import CreateTodo, Directs, SendDirect, UserSearch, NewConversation, TodoDelete

app_name = "chats"


urlpatterns = [
    path("", views.chat, name="message"),
    path("room/<int:pk>", views.Room, name="chat-room"),
    path("join/room/<int:pk>" , views.JoinRoom , name = "join-room") ,
    path("create/room/", views.CreateRoom, name="create-room"),
    path("update/room/<int:pk>", views.UpdateRoom, name="update-room"),
    path('leave-room/<int:pk>/', views.leaveRoom, name='leave-room'),
    path('delete-message/<int:pk>.', views.deleteMessage, name='delete-message'),
    path('send-msg/<int:pk>/', views.SendMSG, name='send-message'),
    
    path("delete/todo", TodoDelete, name="delete-todo"),
    path("create/todo/", CreateTodo, name="create-todo"),

    path('direct/<username>', Directs, name="directs"),
    path('send/', SendDirect, name="send-directs"),
    path('search/', UserSearch, name="search-users"),
    path('new/<username>', NewConversation, name="conversation"),

]

djchatprj/urls.py
# Custom Imports
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("chats.urls")),
    path('user/', include("userauths.urls")),
]


# handler404 = 'base.views.error_404'

if settings.DEBUG:
    urlpatterns +=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userauths/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from userauths import views

app_name = 'userauths'

urlpatterns = [

        # User Profile
        path('profile/update/', views.profileUpdate, name="profile-update"),

        # User Authentication
        path('sign-up/', views.register, name="sign-up"),
        path('sign-in/', auth_views.LoginView.as_view(template_name="userauths/sign-in.html", redirect_authenticated_user=True), name='sign-in'),
        path('sign-out/', auth_views.LogoutView.as_view(template_name="userauths/sign-out.html"), name='sign-out'), 
]

userauths/models.py
from django.db import models
# from django.contrib.auth.models import User
from django.db.models.signals import post_save
# from chats.models import Chatroom
# from article.models import Article
from PIL import Image
from decimal import Decimal
from django.contrib.auth.models import AbstractUser
from django.utils import timezone
from datetime import date
from django.core.cache import cache 
import datetime
from uuid import uuid4

# from marketplace.models import Product

CREATOR_RATING = (
	(Decimal("1.0"), "★☆☆☆☆ (1/5)"),
	(Decimal("2.0"), "★★☆☆☆ (2/5)"),
	(Decimal("3.0"), "★★★☆☆ (3/5)"),
	(Decimal("4.0"), "★★★★☆ (4/5)"),
	(Decimal("5.0"), "★★★★★ (5/5)"),
)

class User(AbstractUser):
    email = models.EmailField(unique=True, null=True)
    username = models.CharField(max_length=10000)
    is_student = models.BooleanField(default=True)
    is_teacher = models.BooleanField(default=False)
    verified = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']
	

    def __str__(self):
        return f"{self.username}"



# uploading user files to a specific directory
def user_directory_path(instance, filename):
	return 'user_{0}/{1}'.format(instance.user.id, filename)


class Profile(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	full_name = models.CharField(max_length=1000)
	bio = models.CharField(max_length=100)
	country = models.CharField(max_length=100, null=True)
	about_me = models.TextField(blank=True, null=True, default="I am a DexxaEd User")
	profile_image = models.ImageField(upload_to=user_directory_path, default="default_profile_image.jpg")


	address = models.CharField(max_length=1000, null=True, blank=True)
	phone = models.CharField(default="+123456789", max_length=100, blank=True, null=True)

	website = models.URLField(default="https://dexxaed.com/", null=True, blank=True)
	facebook = models.URLField(default="https://facebook.com/", null=True, blank=True)
	twitter = models.URLField(default="https://twitter.com/", null=True, blank=True)
	instagram = models.URLField(default="https://instagram.com/", null=True, blank=True)		

	
	
	rooms = models.ManyToManyField('chats.Chatroom', related_name="chat_room",	 blank=True)

	def __str__(self):
		try:
			# Note: you can make this look better and be in a tabular form using Admin (admin.py)
			return f"{self.full_name} - {self.user.username} - {self.user.email} "
		except:
			return self.user.username
	
	def save(self, *args, **kwargs):
		super().save(*args, **kwargs)

		img = Image.open(self.profile_image.path)
		if img.height > 300 or img.width > 300:
			output_size = (300, 300)
			img.thumbnail(output_size)
			img.save(self.profile_image.path)

def create_user_profile(sender, instance, created, **kwargs):
	if created:
		Profile.objects.create(user=instance)

def save_user_profile(sender, instance, **kwargs):
	instance.profile.save()

post_save.connect(create_user_profile, sender=User)
post_save.connect(save_user_profile, sender=User)

class Follow(models.Model):
    follower = models.ForeignKey(User, on_delete=models.CASCADE, related_name='follower')
    following = models.ForeignKey(User, on_delete=models.CASCADE, related_name='following')

userauths/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from userauths.models import User, Profile

class UserRegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        widgets = {
            'username': forms.TextInput(attrs={'placeholder': 'Username', 'class': 'prompt srch_explore'}),
            'email': forms.EmailInput(attrs={'placeholder': 'Email', 'class': 'prompt srch_explore'}),
            'password1': forms.PasswordInput(attrs={'placeholder': 'Enter Password', 'class': 'prompt srch_explore'}),
            'password2': forms.PasswordInput(attrs={'placeholder': 'Confirm Password', 'class': 'prompt srch_explore'}),
        }

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("This email address is already in use.")
        return email

class profileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = [
            'full_name',
            'bio',
            'profile_image', 
            'facebook', 
            'twitter', 
            'instagram',
            'country',
            'address',
            'phone',
            'website',
            ]
        widgets = {
            'full_name': forms.TextInput(attrs={'placeholder': 'Enter Full Name', 'class': 'prompt srch_explore'}),
            'email': forms.EmailInput(attrs={'placeholder': 'Enter Email', 'class': 'prompt srch_explore'}),
        }

class userUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email']
        widgets = {
            'username': forms.TextInput(attrs={'placeholder': 'Enter Username', 'class': 'prompt srch_explore'}),
            'email': forms.EmailInput(attrs={'placeholder': 'Enter Email', 'class': 'prompt srch_explore'}),
        }

userauths/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
User = get_user_model()

from userauths.forms import UserRegisterForm, profileUpdateForm, userUpdateForm
from userauths.models import Profile, Follow

def register(request):
    if request.method == "POST":
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            new_user = form.save()

            # Profile.get_or_create(user=request.user)
            username = form.cleaned_data.get('email')

            messages.success(request, f'Hurray your account was created!!')
            new_user = authenticate(username=form.cleaned_data['email'],
                                    password=form.cleaned_data['password1'],)
            login(request, new_user)
            return redirect('chats:message')
            


    elif request.user.is_authenticated:
        return redirect('base:index')
    else:
        form = UserRegisterForm()
    context = {
        'form': form,
    }
    return render(request, 'userauths/sign-up.html', context)

def profile(request, username):
    if request.user.is_authenticated:
        user = get_object_or_404(User, username=username)
        profile = Profile.objects.get(user=user)
        my_studee_course = profile.favourite_course.all()
        follow_status = Follow.objects.filter(following=user, follower=request.user).exists()

        context = {
        'user':user,
        'profile':profile,

    }
    else:
        user = get_object_or_404(User, username=username)
        profile = Profile.objects.get(user=user)
        
        followers_count = Follow.objects.filter(following=user).count()

        
        context = {
            'profile': profile,
        }
    return render(request, 'userauths/profile.html', context)



@login_required
def profileUpdate(request):
    profile = Profile.objects.get(user=request.user)

    if request.method == "POST":
        p_form = profileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
        u_form = userUpdateForm(request.POST, instance=request.user)
        if p_form.is_valid() and u_form.is_valid():
            p_form.save()
            u_form.save()
            return redirect('chats:message')
    else:
        p_form = profileUpdateForm(instance=request.user.profile)
        u_form = userUpdateForm(instance=request.user)
    
    context = {
        'p_forms': p_form,
        'u_forms': u_form,
    }
    return render(request, 'userauths/profile-update.html', context)


@login_required
def follow(request, username, option):
    user = request.user.username
    following = get_object_or_404(User, username=username)

    try:
        f, created = Follow.objects.get_or_create(follower=request.user, following=following)

        if int(option) == 0:
            f.delete()
        else:
            pass
            
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
        
    except User.DoesNotExist:
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def error404View(request):
    return render(request, 'base/404.html')

templates/userauths/email-verification.html
{% autoescape off %}

Hello,

Thank you for registering on our website

Please be so kind as to verify your email by clicking the link below:

https://{{domain}}{% url 'email-verification' uidb64=uid token=token %}

{% endautoescape %}

templates/userauths/profile-update.html
{% load static %}
{% load crispy_forms_tags %}

<!DOCTYPE html>
<html lang="en">
  {% include 'chats/head.html' %}

  <!-- login page start //-->
  <body>
    <div class="login-page2 animat-rate">
      <div class="login-content-main"> 
        <div class="login-content2">
          <div class="theme-tab">       
            <ul class="nav nav-tabs" id="myTab" role="tablist">
                <li class="nav-item"><a class="nav-link" id="login-tab" data-toggle="tab" href="{% url 'chats:message' %}" role="tab" aria-selected="false">Go back</a></li>
  
            </ul>
          </div>
        </div>
        <div class="login-content">
          <div class="login-content-header"><img class="img-fluid" src="{{ request.user.profile.profile_image.url }}" style="height: 70px; width: 70px; object-fit: cover; border-radius: 50px;" alt="images"></div>
          <h3>Hello there 👋</h3>
          <h4>Let's edit your profile</h4>
          {% if form.errors %}
            <div class="alert alert-danger"> 
              <strong>{{ form.errors }}</strong>
            </div>
            {% endif %}
          <form class="form2" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
                {{ u_form.full_name}}
            </div>
            <div class="form-group">
                {{ p_form}}
            </div>
            <div class="form-group mb-0">
              <div class="buttons"><button type="submit" class="btn button-effect btn-primary" >Save Edit</button></div>
            </div>
          </form>
        </div>
      </div>
      <div class="animation-block">
        <div class="bg_circle">
          <div></div>
          <div></div>
          <div></div>
          <div></div>
          <div></div>
          <div></div>
          <div></div>
          <div></div>
          <div></div>
          <div></div>
          <div></div>
        </div>
        <div class="cross"></div>
        <div class="cross1"></div>
        <div class="cross2"></div>
        <div class="dot"></div>
        <div class="dot1"></div>
        <div class="top-circle"></div>
        <div class="center-circle"></div>
        <div class="bottom-circle1"></div>
        <div class="right-circle"></div>
        <div class="right-circle1"></div>
      </div>
    </div>
  </body>
</html>

templates/userauths/sign-in.html
{% load static %}
{% load crispy_forms_tags %}

<!DOCTYPE html>
<html lang="en">
  {% include 'chats/head.html' %}

  <!-- login page start //-->
  <body class="sidebar-active dark">
    <div class="login-page2 animat-rate">
      <div class="login-content-main"> 
        <div class="login-content2">
          <div class="theme-tab">       
            <ul class="nav nav-tabs" id="myTab" role="tablist">
                <li class="nav-item"><a class="nav-link" id="login-tab" data-toggle="tab" href="{% url 'userauths:sign-in' %}" role="tab" aria-selected="false">login</a></li>
                <li class="nav-item"><a class="nav-link active" id="signup-tab" data-toggle="tab" href="{% url 'userauths:sign-up' %}" role="tab" aria-selected="true">Signup</a></li>
              
            </ul>
          </div>
        </div>
        <div class="login-content">
          <div class="login-content-header"><img class="img-fluid" src="{% static 'assets/images/logo/STAT.png' %}" alt="images"></div>
          <h3>Hello there,</h3>
          <h4>Welcome to STAT Chat App! Please login to your account.</h4>
          {% if form.errors %}
            <div class="alert alert-danger"> 
              <strong>{{ form.errors }}</strong>
            </div>
            {% endif %}
          <form class="form2" method="POST">
            {% csrf_token %}
           
            <div class="form-group">
                <label for="">Email</label>
                {{form.username}}
            </div>
            
            
            <div class="form-group">
                  <label for="">Password</label>
                {{form.password}}
              </div>
            
            <div class="form-group">
              <div class="rememberchk">
                <div class="form-check">
                  <input class="form-check-input" id="gridCheck1" type="checkbox">
                  <label class="form-check-label" for="gridCheck1">Remember Me.</label>
                  <h6>Forgot Password?</h6>
                </div>
              </div>
            </div>
            <ul class="medialogo">
              <li><a class="icon-btn btn-facebook button-effect rouded15" href="#"><i class="fa fa-facebook-f"></i></a></li>
              <li><a class="icon-btn btn-danger button-effect rouded15" href="#"><i class="fa fa-google"></i></a></li>
              <li><a class="icon-btn btn-primary button-effect rouded15" href="#"><i class="fa fa-twitter"></i></a></li>
            </ul>
            <div class="form-group mb-0">
              <div class="buttons"><button type="submit" class="btn button-effect btn-primary" >Login</button></div>
            </div>
          </form>
        </div>
      </div>
      <div class="animation-block">
        <div class="bg_circle">
          <div></div>
          <div></div>
          <div></div>
          <div></div>
          <div></div>
          <div></div>
          <div></div>
          <div></div>
          <div></div>
          <div></div>
          <div></div>
        </div>
        <div class="cross"></div>
        <div class="cross1"></div>
        <div class="cross2"></div>
        <div class="dot"></div>
        <div class="dot1"></div>
        <div class="top-circle"></div>
        <div class="center-circle"></div>
        <div class="bottom-circle1"></div>
        <div class="right-circle"></div>
        <div class="right-circle1"></div>
      </div>
    </div>
  </body>
</html>

templates/userauths/sign-up.html
{% load static %}
{% load crispy_forms_tags %}

<!DOCTYPE html>
<html lang="en">
  {% include 'chats/head.html' %}
  
  <!-- login page start //-->
  <body class="dark">
    <div class="login-page2 animat-rate">
      <div class="login-content-main"> 
        <div class="login-content2">
          <div class="theme-tab">       
            <ul class="nav nav-tabs" id="myTab" role="tablist">
                <li class="nav-item"><a class="nav-link" id="login-tab" data-toggle="tab" href="{% url 'userauths:sign-in' %}" role="tab" aria-selected="false">login</a></li>
                <li class="nav-item"><a class="nav-link active" id="signup-tab" data-toggle="tab" href="{% url 'userauths:sign-up' %}" role="tab" aria-selected="true">Signup</a></li>
  
            </ul>
          </div>
        </div>
        <div class="login-content">
          <div class="login-content-header"><img class="img-fluid" src="{% static 'assets/images/logo/STAT.png' %}" alt="images"></div>
          <h3>Hello there,</h3>
          <h4>Welcome to STAT Chat App! Create a free account now.</h4>
          {% if form.errors %}
            <div class="alert alert-danger"> 
              <strong>{{ form.errors }}</strong>
            </div>
            {% endif %}
          <form class="form2" method="POST">
            {% csrf_token %}
            
            <div class="form-group">
              <label class="col-form-label" for="inputEmail">Email</label>
              <span></span>
              {{form.email}}
            </div>

            <div class="form-group">
              <label class="col-form-label" for="inputEmail">Username</label>
              <span></span>
                {{form.username}}
              </div>

              <div class="form-group">
                 <label class="col-form-label" for="inputEmail">Password</label>
                 <span></span>
                {{form.password1}}
              </div>

              <div class="form-group">
                <label class="col-form-label" for="inputEmail">Confrim Password</label>
                <span></span>
                {{form.password2}}
              </div>
            
            <div class="form-group">
              <div class="rememberchk">
                <div class="form-check">
                  <input class="form-check-input" id="gridCheck1" type="checkbox">
                  <label class="form-check-label" for="gridCheck1">Remember Me.</label>
                  <h6>Forgot Password?</h6>
                </div>
              </div>
            </div>
            <ul class="medialogo">
              <li><a class="icon-btn btn-facebook button-effect rouded15" href="#"><i class="fa fa-facebook-f"></i></a></li>
              <li><a class="icon-btn btn-danger button-effect rouded15" href="#"><i class="fa fa-google"></i></a></li>
              <li><a class="icon-btn btn-primary button-effect rouded15" href="#"><i class="fa fa-twitter"></i></a></li>
            </ul>
            <div class="form-group mb-0">
              <div class="buttons"><button type="submit" class="btn button-effect btn-primary" >Signup</button></div>
            </div>
          </form>
        </div>
      </div>
      <div class="animation-block">
        <div class="bg_circle">
          <div></div>
          <div></div>
          <div></div>
          <div></div>
          <div></div>
          <div></div>
          <div></div>
          <div></div>
          <div></div>
          <div></div>
          <div></div>
        </div>
        <div class="cross"></div>
        <div class="cross1"></div>
        <div class="cross2"></div>
        <div class="dot"></div>
        <div class="dot1"></div>
        <div class="top-circle"></div>
        <div class="center-circle"></div>
        <div class="bottom-circle1"></div>
        <div class="right-circle"></div>
        <div class="right-circle1"></div>
      </div>
    </div>
  </body>
</html>