chats/urls.py
from django.urls import path
from chats import views
from chats.views import CreateTodo, Directs, SendDirect, UserSearch, NewConversation, TodoDelete

app_name = "chats"


urlpatterns = [
    path("", views.chat, name="message"),
    path("room/<int:pk>", views.Room, name="chat-room"),
    path("join/room/<int:pk>" , views.JoinRoom , name = "join-room") ,
    path("create/room/", views.CreateRoom, name="create-room"),
    path("update/room/<int:pk>", views.UpdateRoom, name="update-room"),
    path('leave-room/<int:pk>/', views.leaveRoom, name='leave-room'),
    path('delete-message/<int:pk>.', views.deleteMessage, name='delete-message'),
    path('send-msg/<int:pk>/', views.SendMSG, name='send-message'),
    
    path("delete/todo", TodoDelete, name="delete-todo"),
    path("create/todo/", CreateTodo, name="create-todo"),

    path('direct/<username>', Directs, name="directs"),
    path('send/', SendDirect, name="send-directs"),
    path('search/', UserSearch, name="search-users"),
    path('new/<username>', NewConversation, name="conversation"),

]

djchatprj/urls.py
# Custom Imports
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("chats.urls")),
    path('user/', include("userauths.urls")),
]


# handler404 = 'base.views.error_404'

if settings.DEBUG:
    urlpatterns +=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chats/models.py
from distutils.command.upload import upload
from django.db import models

from email.policy import default
from django.db import models
from PIL import Image
from django.db.models import Max
from django.forms import DateTimeField
from django.conf import settings
from django.db.models.signals import post_save
from django.contrib.auth import get_user_model

from userauths.models import user_directory_path

User = settings.AUTH_USER_MODEL
UserModel = get_user_model()

class Topic(models.Model) : 
    name = models.CharField(max_length = 100) 
    created = models.DateTimeField(auto_now_add = True)
    class Meta : 
        ordering = ["created"]
    
    def __str__(self): 
        return str(self.name)


class Chatroom(models.Model) : 
    image = models.ImageField(default="default-room.jpg", upload_to="room_thumbnails")
    host = models.ForeignKey(User , on_delete = models.CASCADE ) 
    topic = models.ForeignKey("chats.Topic", verbose_name="topic", on_delete=models.SET_NULL , null = True, related_name="chatroom_topic")
    roomname = models.CharField(max_length = 200 )
    description = models.TextField(null = True ,  blank = True)
    participants = models.ManyToManyField(User, verbose_name="participants" , related_name = "participants"  )
    updated = models.DateTimeField(auto_now = True)
    created = models.DateTimeField(auto_now_add = True)
    
    class Meta : 
        ordering = ["-updated" , "-created"]
    
    def __str__(self) : 
        return str(self.roomname)  + " created by -> " + str(self.host) + " on " + str(self.topic) 
    
class Message(models.Model) : 
    user = models.ForeignKey(User , on_delete = models.CASCADE) 
    room = models.ForeignKey(Chatroom , on_delete = models.CASCADE) 
    body = models.TextField()
    udpated = models.DateTimeField(auto_now = True)
    created = models.DateTimeField(auto_now_add = True) 
    
    class Meta: 
        ordering = ["udpated" , "created"]
    
    def __str__(self) : 
        return str(self.user) + "texted ->" + str(self.body)[:50]



class Messages(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name="from_user")
    reciepient = models.ForeignKey(User, on_delete=models.CASCADE, related_name="to_user")
    body = models.TextField(null=True)
    date = models.DateTimeField(auto_now_add=True)
    is_read = models.BooleanField(default=False)

    def sender_message(from_user, to_user, body):
        sender_message = Messages(
            user=from_user,
            sender = from_user,
            reciepient = to_user,
            body = body,
            is_read = True
            )
        sender_message.save()
    
        reciepient_message = Messages(
            user=to_user,
            sender = from_user,
            reciepient = from_user,
            body = body,
            is_read = True
            )
        reciepient_message.save()
        return sender_message

    def get_message(user):
        users = []
        messages = Messages.objects.filter(user=user).values('reciepient').annotate(last=Max('date')).order_by('-last')
        for message in messages:
            users.append({
                'user': UserModel.objects.get(pk=message['reciepient']),
                'last': message['last'],
                'unread': Messages.objects.filter(user=user, reciepient__pk=message['reciepient'], is_read=False).count()
            })
        return users


class Todos(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    todo = models.CharField(max_length=1000)
    completed = models.BooleanField(default=True)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.todo[:20]

chats/forms.py
from django import forms
from chats.models import Chatroom


class ChatRoomForm(forms.ModelForm) : 
    class Meta : 
        model = Chatroom
        fields = "__all__"
        exclude = ["host" ,"participants"]
       

chats/views.py
from django.shortcuts import render
from django.conf import settings
from django.shortcuts import get_object_or_404, redirect, render
from django.db.models import Q , Count
from django.contrib import messages 
from django.contrib.auth.decorators import login_required 
from django.db.models import Q
from django.core.paginator import Paginator
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.db.models.signals import post_save

from chats.forms import ChatRoomForm
from chats.models import Topic , Message , Chatroom, Messages, Todos
from userauths.models import Profile
from django.views.decorators.csrf import csrf_exempt


# Importing the User Models
from django.contrib.auth import get_user_model
User = get_user_model()


@login_required
def chat(request):
    if request.user.is_authenticated:
        q = request.GET.get("q").strip() if request.GET.get("q") != None else ""
        rooms = Chatroom.objects.filter(
            Q(topic__name__icontains=q) |
            Q(roomname__icontains=q) |
            Q(description__icontains=q)
        )
        rooms_count = rooms.count()
        rooms = rooms[:6]
        topics = Topic.objects.all()
        topics_count = topics.count()
        topics = topics[:5]
        room_messages = Message.objects.filter(
            Q(room__topic__name__icontains = q)
        )[:5]

        todos = Todos.objects.all()
        

        user = request.user
        messages = Messages.get_message(user=request.user)
        active_direct = None
        directs = None
        profile = get_object_or_404(Profile, user=user)

        all_users = User.objects.all()

        if messages:
            message = messages[0]
            active_direct = message['user'].username
            directs = Messages.objects.filter(user=request.user, reciepient=message['user'])
            directs.update(is_read=True)

            for message in messages:
                if message['user'].username == active_direct:
                    message['unread'] = 0

        context = {

            "todos": todos, 
            "all_users": all_users, 
            "rooms": rooms, 
            "topics": topics, 
            "room_messages" : room_messages , 
            "rooms_count": rooms_count , 
            "topics_count" : topics_count,
            'directs':directs,
            'messages': messages,
            'active_direct': active_direct,
            'profile': profile,
            
            }
        return render(request, "chats/chat-home.html", context)



def leaveRoom(request, pk):
    room = Chatroom.objects.get(id=pk)
    profile = Profile.objects.get(user=request.user)

    if request.user.is_authenticated:
        room.participants.remove(request.user)
        profile.rooms.remove(room)

        messages.success(request, f'You left {room.roomname} successfully.')
        return redirect("chats:chat-room", room.pk)
    else:
        messages.warning(request, f'You need to login before you can join any room.')
        return redirect("userauths:sign-in")


def deleteMessage(request, pk):
    messages = Messages.objects.get(id=pk)
    messages.delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def Room(request, pk):
    user = request.user 
    room = Chatroom.objects.get(id = pk)
    if not room : 
        return redirect("chats:message")
    room_messages = room.message_set.all()[:20]
    
    all_users = User.objects.all()

    # all Rooms
    q = request.GET.get("q").strip() if request.GET.get("q") != None else ""
    rooms = Chatroom.objects.filter(
        Q(topic__name__icontains=q) |
        Q(roomname__icontains=q) |
        Q(description__icontains=q)
    )
    rooms_count = rooms.count()
    rooms = rooms[:6]
    topics = Topic.objects.all()
    topics_count = topics.count()
    topics = topics[:5]

    context = {
        "room": room ,
        "room_messages" : room_messages ,
        "user" : user,
        "all_users" : all_users,
        "rooms": rooms, 
        "topics": topics, 
        "rooms_count": rooms_count , 
        "topics_count" : topics_count
    
    } 
    return render(request, "chats/chat-room.html", context)



@login_required
def JoinRoom(request , pk) : 
    profile = Profile.objects.get(user=request.user)
    room = Chatroom.objects.get(id = pk)

    if not room : 
        return redirect("chats:message")

    if request.user.is_authenticated : 
        room.participants.add(request.user)
        profile.rooms.add(room)
        messages.success(request, f'You have joined {room.roomname}.')
    else : 
        messages.warning(request , "You have to Login first in order to join a room !") 

    return redirect("chats:chat-room" , pk=pk)



@login_required
def CreateRoom(request):
    topics = Topic.objects.all()
    if request.method == "POST":
        form = ChatRoomForm(request.POST, request.FILES)
        topic_name = request.POST.get("topic")
        topic , created = Topic.objects.get_or_create(name = topic_name )
        
        new_room = Chatroom.objects.create(
            host=request.user , 
            roomname = request.POST.get("roomname") , 
            topic = topic , 
            description = request.POST.get("description" ),
            image = request.FILES.get("image" )
        )
        new_room.participants.add(request.user.id)
        
        return redirect("chats:chat-room" , pk=new_room.id)
    else:
        form = ChatRoomForm()
    context = {"form": form, "button_value": "Create" , "topics" : topics}
    return render(request, "chats/room_form.html", context)

@login_required 
def UpdateRoom(request, pk):
    room = Chatroom.objects.get(id=pk)
    if not room : 
        return redirect("chats:message")
    form = ChatRoomForm(instance = room)
    if request.user != room.host :
        messages.error(request , "You are not allowed to Edit Room Settings !") 
        return redirect("chats:message")

    if request.method == "POST":
        room.roomname = request.POST.get("roomname")
        room.topic , created = Topic.objects.get_or_create(name = request.POST.get("topic"))
        room.description = request.POST.get("description")

        room.save()
        return redirect("chats:chat-room" , pk=room.id)
    context = {"form": form, "button_value": "Update"  , "room" : room }
    return render(request, "chats/room_update_form.html", context)


def SendMSG(request, pk):
    
    if request.method == "POST":
        user = request.user
        room = Chatroom.objects.get(id=pk)

        body = request.POST.get("body")
        new_chat = Message.objects.create(user=user, room=room, body=body)
        
        # return redirect('message')
        success = "Message Sent."
        return HttpResponse(success)


@login_required
def Directs(request, username):
    user  = request.user
    messages = Messages.get_message(user=user)
    active_direct = username
    directs = Messages.objects.filter(user=user, reciepient__username=username)  
    directs.update(is_read=True)


    q = request.GET.get("q").strip() if request.GET.get("q") != None else ""
    rooms = Chatroom.objects.filter(
        Q(topic__name__icontains=q) |
        Q(roomname__icontains=q) |
        Q(description__icontains=q)
    )
    rooms_count = rooms.count()
    rooms = rooms[:6]
    topics = Topic.objects.all()
    topics_count = topics.count()
    topics = topics[:5]
    room_messages = Message.objects.filter(
        Q(room__topic__name__icontains = q)
    )[:5]

    all_users = User.objects.all()


    for message in messages:
            if message['user'].username == username:
                message['unread'] = 0
    context = {
        'all_users': all_users,
        'directs': directs,
        'messages': messages,
        'active_direct': active_direct,
        "room_messages" : room_messages ,
        "user" : user,
        "rooms": rooms, 
        "topics": topics, 
        "rooms_count": rooms_count , 
        "topics_count" : topics_count
    }
    return render(request, 'chats/chat-home.html', context)

def SendDirect(request):
    
    if request.method == "POST":
        from_user = request.user
        to_user_username = request.POST['to_user']
        body = request.POST['body']

        to_user = User.objects.get(username=to_user_username)
        Messages.sender_message(from_user, to_user, body)
        # return redirect('message')
        success = "Message Sent."
        return HttpResponse(success)

def UserSearch(request):
    query = request.GET.get('q')
    # profile = Profile.objects.all()

    context = {}
    if query:
        users = User.objects.filter(Q(username__icontains=query))
        profiles = Profile.objects.filter(Q(full_name__icontains=query))

        # Paginator
        # paginator = Paginator(users, 8)
        # page_number = request.GET.get('page')
        # users_paginator = paginator.get_page(page_number)

        context = {
            'users': users,
            'profiles': profiles,
            'query':query,
            }

    return render(request, 'chats/search.html', context)

def NewConversation(request, username):
    from_user = request.user
    body = ''
    try:
        to_user = User.objects.get(username=username)
    except Exception as e:
        return redirect('search-users')
    if from_user != to_user:
        Messages.sender_message(from_user, to_user, body)
    return redirect('message')

@csrf_exempt
def TodoDelete(request):
    if request.method == "POST":
        id = request.POST.get("cid")
        todo = Todos.objects.get(pk=id)
        todo.delete()
        return JsonResponse({"status":1})
    else:
        return JsonResponse({"status": 0})


def CreateTodo(request):
    if request.method == "POST":
        todo = request.POST.get("todo")
        user = request.user

        new_todo = Todos.objects.create(user=user, todo=todo)
        new_todo.save()
        success = "Todo Added"

templates/chats/footer.html
    {% load static %}
    <script src="{% static 'assets/js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'assets/js/owl.carousel.js' %}"></script>
    <script src="{% static 'assets/js/popper.min.js' %}"></script>
    <script src="{% static 'assets/js/tippy-bundle.iife.min.js' %}"></script>
    <script src="{% static 'assets/js/bootstrap.js' %}"></script>
    <script src="{% static 'assets/js/switchery.js' %}"></script>
    <script src="{% static 'assets/js/easytimer.min.js' %}"></script>
    <script src="{% static 'assets/js/index.js' %}"></script>
    <script src="{% static 'assets/js/feather-icon/feather.min.js' %}"></script>
    <script src="{% static 'assets/js/feather-icon/feather-icon.js' %}"></script>
    <script src="{% static 'assets/js/ckeditor/ckeditor.js' %}"></script>
    <script src="{% static 'assets/js/ckeditor/styles.js' %}"></script>
    <script src="{% static 'assets/js/ckeditor/adapters/jquery.js' %}"></script>
    <script src="{% static 'assets/js/ckeditor/ckeditor.custom.js' %}"></script>
    <script src="{% static 'assets/js/date-picker/datepicker.js' %}"></script>
    <script src="{% static 'assets/js/date-picker/datepicker.en.js' %}"></script>
    <script src="{% static 'assets/js/date-picker/datepicker.custom.js' %}"></script>
    <script src="{% static 'assets/js/tour/intro.js' %}"></script>
    <script src="{% static 'assets/js/tour/intro-init.js' %}"></script>
    <script src="{% static 'assets/js/jquery.magnific-popup.js' %}"></script>
    <script src="{% static 'assets/js/zoom-gallery.js' %}"></script>
    <script src="{% static 'assets/js/script.js' %}"></script>

templates/chats/head.html
{% load static %}
<head>
    <title>STAT Chat App</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="description" content="D-Chat">
    <meta name="keywords" content="D-Chat">
    <meta name="author" content="D-Chat">
    <link rel="icon" href="assets/images/favicon/favicon.png" type="image/x-icon">
    <link rel="shortcut icon" href="assets/images/favicon/favicon.png" type="image/x-icon">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,500,600,700,800&amp;display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,500,600&amp;display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Rubik:300,300i,400,400i,500,500i,700,700i,900,900i&amp;display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/date-picker.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/magnific-popup.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/style.css' %}" media="screen" id="color">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/tour.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <link rel="stylesheet" type="text/css" href="{% static 'assets/js/ckeditor/skins/moono-lisa/editor.css?t=HBDD' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/js/ckeditor/plugins/scayt/skins/moono-lisa/scayt.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/js/ckeditor/plugins/scayt/dialogs/dialog.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/js/ckeditor/plugins/tableselection/styles/tableselection.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/js/ckeditor/plugins/wsc/skins/moono-lisa/wsc.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/js/ckeditor/plugins/copyformatting/styles/copyformatting.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/date-picker.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/magnific-popup.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/style.css' %}" media="screen" id="color">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/tour.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/js/ckeditor/skins/moono-lisa/editor.css?t=HBDD' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/js/ckeditor/plugins/scayt/skins/moono-lisa/scayt.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/js/ckeditor/plugins/scayt/dialogs/dialog.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/js/ckeditor/plugins/tableselection/styles/tableselection.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/js/ckeditor/plugins/wsc/skins/moono-lisa/wsc.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/js/ckeditor/plugins/copyformatting/styles/copyformatting.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
</head>

templates/chats/room_form.html
{% load crispy_forms_tags %}
{% load static %}



<!DOCTYPE html>
<html lang="en">
  {% include 'chats/head.html' %}

  <!-- login page start //-->
  <body class="dark">
    <div class="login-page2 animat-rate" style="padding-top: 70px;">
      <div class="login-content-main"> 
        
        <div class="login-content">
          <!-- <div class="login-content-header"><img class="img-fluid" src="../assets/images/logo/landing-landing-logo.png" alt="images"></div> -->
          <h3>Create A New Group</h3>
          <h4>Create group for your students, buddies or team members.</h4>
          <form class="form2" method="POST" enctype="multipart/form-data">{% csrf_token %}
            
            {% if form.errors %}
            <div class="alert alert-danger"> 
              <strong>{{ form.errors }}</strong>
            </div>
            {% endif %}
            <div class="form-group">
              <label class="col-form-label" for="inputEmail3">Topic</label>
              <input value = "{{room.topic.name}}" type="text" name="topic" list="topic-list" placeholder = "Topic for the room.." class="form-control" required />
              <datalist id="topic-list">
                <select id="room_topic"> 
                    {% for topic in topics %}
                  <option value="{{topic.name}}">{{topic.name}}</option>
                {% endfor %}
                </select>
              </datalist>
            </div>

            <div class="form-group">
              <label class="col-form-label" for="inputEmail3">Room Name</label>
              {{form.roomname}}
            </div>

            <div class="form-group">
              <label class="col-form-label" for="inputEmail3">Room Description</label>
              {{form.description}}
            </div>

            <div class="form-group">
              <label class="col-form-label" for="inputEmail3">Room Thumbnail</label>
              {{form.image}}
            </div>

            <div class="form-group mb-0">
              <div class="buttons"><button class="btn button-effect btn-primary" type="submit">Create Group</button></div>
            </div>
            <br><br>
            <div class="login-content2">
              <div class="theme-tab">       
                <ul class="nav nav-tabs" id="myTab" role="tablist">
                  <li class="nav-item">
                    <a class="nav-link" id="login-tab" data-toggle="tab" href="{% url 'chats:message' %}" role="tab" aria-selected="false">Go Back</a>
                  </li>
                  <!-- <li class="nav-item"><a class="nav-link active" id="signup-tab" data-toggle="tab" href="signup-2.html" role="tab" aria-selected="true">Signup</a></li> -->
                </ul>
              </div>
            </div>
          </form>
        </div>
      </div>
      <div class="animation-block">
        <div class="bg_circle">
          <div></div>
          <div></div>
          <div></div>
          <div></div>
          <div></div>
          <div></div>
          <div></div>
          <div></div>
          <div></div>
          <div></div>
          <div></div>
        </div>
        <div class="cross"></div>
        <div class="cross1"></div>
        <div class="cross2"></div>
        <div class="dot"></div>
        <div class="dot1"></div>
        <div class="top-circle"></div>
        <div class="center-circle"></div>
        <div class="bottom-circle1"></div>
        <div class="right-circle"></div>
        <div class="right-circle1"></div>
        <!-- <div class="quarterCircle"></div><img class="cloud-logo" src="../assets/images/login_signup/2.png" alt="login logo"/><img class="cloud-logo1" src="../assets/images/login_signup/2.png" alt="login logo"/><img class="cloud-logo2" src="../assets/images/login_signup/2.png" alt="login logo"/><img class="cloud-logo3" src="../assets/images/login_signup/2.png" alt="login logo"/><img class="cloud-logo4" src="../assets/images/login_signup/2.png" alt="login logo"/><img class="cloud-logo5" src="../assets/images/login_signup/2.png" alt="login logo"/> -->
      </div>
    </div>
  </body>
</html>

templates/chats/search.html
{% load crispy_forms_tags %}



{% load static %}



<!DOCTYPE html>
<html lang="en">
{% include 'chats/head.html' %}
  
  <!-- login page start //-->
  <body>
    <div class="login-page2 animat-rate">
      <div class="login-content-main"> 
        <div class="login-content2">
          <div class="theme-tab">       
            <ul class="nav nav-tabs" id="myTab" role="tablist">
              <li class="nav-item"><a class="nav-link" id="login-tab" data-toggle="tab" href="{% url 'chats:message' %}" role="tab" aria-selected="false">Go Back</a></li>
              <!-- <li class="nav-item"><a class="nav-link active" id="signup-tab" data-toggle="tab" href="signup-2.html" role="tab" aria-selected="true">Signup</a></li> -->
            </ul>
          </div>
        </div>
        <div class="login-content">
          <!-- <div class="login-content-header"><img class="img-fluid" src="../assets/images/logo/landing-landing-logo.png" alt="images"></div> -->
          <!-- <h3>All <b>{{query}}</b></h3> -->
          
          <div class="theme-tab tab-sm chat-tabs">
            <ul class="nav nav-tabs" id="myTab" role="tablist">
                <li class="nav-item text-center" data-to="chat-content"><a class="nav-link button-effect active" id="chat-tab" data-toggle="tab" href="#chat" role="tab" aria-controls="chat" aria-selected="true"><i data-feather="message-square"> </i>Search Results for {{query}}</a></li>
                
            </ul>
            <div class="tab-content" id="myTabContent">
                <div class="tab-pane fade show active" id="chat" role="tabpanel" aria-labelledby="chat-tab">
                    <div class="theme-tab">
                        <ul class="nav nav-tabs" id="myTab1" role="tablist">
                        </ul>
                        <div class="tab-content" id="myTabContent1">
                            <div class="tab-pane fade show active" id="direct" role="tabpanel" aria-labelledby="direct-tab">
                                <ul class="chat-main">

                                    {% for user in users %}
                                        <a href="{% url 'chats:directs' user.username %}">
                                            <li class="active mb-1" data-to="chating">
                                                <div class="chat-box">
                                                    <div class="profile"><img class="bg-img" style="width: 50px; height: 50px; border-radius: 10px;" src="{{user.profile.profile_image.url}}" alt="{{message.user.profile.full_name}}" /></div>
                                                    <div class="details">
                                                        {% if user.profile.full_name %}
                                                        <h5>{{user.profile.full_name|title}}</h5>
                                                        {% else %}
                                                        <h5>{{user.username|title}}</h5>
                                                        {% endif %}
                                                        <h6>@{{user.username}}</h6>
                                                    </div>
                                                    <div class="date-status"><i class="ti-pin2"></i>
                                                        <h6>Message</h6>
                                                    </div>
                                                </div>
                                            </li>
                                        </a>
                                        {% empty %}
                                        <li class="active">
                                            <h5>No Result for <i><b>{{query}}</b></i></h5>
                                        </li>
                                    {% endfor %}

                                   
                                    
                                    
                                </ul>
                            </div>
                            
                        </div>
                    </div>
                </div>
               
            </div>
        </div>
        </div>
      </div>
      <div class="animation-block">
        <div class="bg_circle">
          <div></div>
          <div></div>
          <div></div>
          <div></div>
          <div></div>
          <div></div>
          <div></div>
          <div></div>
          <div></div>
          <div></div>
          <div></div>
        </div>
        <div class="cross"></div>
        <div class="cross1"></div>
        <div class="cross2"></div>
        <div class="dot"></div>
        <div class="dot1"></div>
        <div class="top-circle"></div>
        <div class="center-circle"></div>
        <div class="bottom-circle1"></div>
        <div class="right-circle"></div>
        <div class="right-circle1"></div>
        <!-- <div class="quarterCircle"></div><img class="cloud-logo" src="../assets/images/login_signup/2.png" alt="login logo"/><img class="cloud-logo1" src="../assets/images/login_signup/2.png" alt="login logo"/><img class="cloud-logo2" src="../assets/images/login_signup/2.png" alt="login logo"/><img class="cloud-logo3" src="../assets/images/login_signup/2.png" alt="login logo"/><img class="cloud-logo4" src="../assets/images/login_signup/2.png" alt="login logo"/><img class="cloud-logo5" src="../assets/images/login_signup/2.png" alt="login logo"/> -->
      </div>
    </div>
  </body>
</html>